import React,{useState,useEffect} from 'react'
import { Loader,Card,FormField} from '../components'

const RenderCards = ({ data, title }) => {
  if (data?.length >= 9) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }

  return (
    <h2 className="mt-5 font-bold uppercase text-[#6449ff] text-xl">
      {title}
    </h2>
  );
};


function Home() {
  const [loading,setLoading]=useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText,setSearchText]= useState('asd');
  return (
    <section>
      <div className='max-w-7xl mx-auto'>
        <h1 className='font-extrabold text-[#A04732] text-[30px]'>THE COMMUNITY SHOWCASE</h1>
        <p className='mt-2 text-[#e0a99a] text-[14px] w-full max-w-none whitespace-nowrap'>
            Browse through a collection of imaginative and visually stunning images generated by PixAi
        </p>
      </div>

    <div className='mt-16'>
      <FormField/>
    </div>

    <div className='mt-10'>
      {loading ? (
        <div className='flex justify-center items-center'>
          <Loader/>
         </div>
      ) : (
        <>
            {searchText && (
              <h2 className='font-medium text-[#e0a99a] text-xl mb-3'>
                Showing results for <span className='text-[#A04732]'>{searchText}</span>
              </h2>
            )}

            <div className='grid lg:grid-cols-4 sm:grid-ols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
            {searchText ? (
              <RenderCards data={[]} title="No search results found" />
            ) : (
              <RenderCards data={[]} title="No posts found" />
            )}

            </div>
          </>
      )}
    </div>

    </section>
  )
}

export default Home